name: eazel7/origami
author:
  name: Diego Perez
  email: eazel7@gmail.com
  url: 'https://eazel7-blog.rhcloud.com'
copyright: 2015 Diego Perez
description: 'Origami application platform. Related repository: https://github.com/eazel7/origami-packs'
